Feature/wks 343 periodic
cultuurnet/calendar-summary-v3 pull request #1
Opened 2017-11-27 13:54 UTC by ThomasJacobsWK

2017-11-27 14:01 UTC, ThomasJacobsWK commented
Travis geeft momenteel issues over PermanentFormatterInterface omdat ik de namespace veranderd heb van calendar summary. De failed checks kan je dus voorlopig negeren (Permanent doe ik in aparte feature branch).

2017-11-27 17:16 UTC, zuuperman requested changes
Mostly good. All remarks about the same thing. Can be merged after replacing them with datetime objects

2017-11-27 17:16 UTC, zuuperman commented on src/Periodic/LargePeriodicHTMLFormatter.php
> +        $outputDates .= '<time itemprop="startDate" datetime="' . date("Y-m-d", $dateFromTimestamp) . '">';
No need to go back to a timestamp. You can also do:
$dateFrom->format('Y-m-d')

Same for $dateTo

2017-11-27 17:16 UTC, zuuperman commented on src/Periodic/LargePeriodicHTMLFormatter.php
> +        $intlDateFrom =$fmt->format($dateFromTimestamp);
Intl also supports dateTime objects. This works also:
        $intlDateFrom = $dateFormatter->format($dateFrom);
        $intlDateTo = $dateFormatter->format($dateTo);

2017-11-27 17:16 UTC, zuuperman commented on src/Periodic/LargePeriodicPlainTextFormatter.php
> +        $dateFromTimestamp = $dateFrom->getTimestamp();
Same remark as for large period. Give the datetime object to intl, instead of timestamp

2017-11-27 17:16 UTC, zuuperman commented on src/Periodic/MediumPeriodicHTMLFormatter.php
> +        $dateFrom = $offer->getStartDate();
Same remark, use the datetime object

2017-11-27 17:16 UTC, zuuperman commented on src/Periodic/MediumPeriodicPlainTextFormatter.php
> +        $dateFromTimestamp = $dateFrom->getTimestamp();
Same remark, use the datetime object.

2017-11-28 09:22 UTC, ThomasJacobsWK commented
I performed the requested changes

2018-01-11 18:47 UTC, merged